create extension if not exists pgcrypto;

create table if not exists public.ingest_files (
  id uuid primary key default gen_random_uuid(),
  run_date date not null,
  message_id text not null,
  thread_id text,
  message_date timestamptz,
  message_subject text not null,
  matched_topic text not null,
  attachment_name text not null,
  attachment_type text not null check (attachment_type in ('xlsx', 'csv')),
  status text not null check (status in ('ingested', 'skipped', 'error')),
  header_json jsonb not null default '[]'::jsonb,
  row_count integer not null default 0,
  error_text text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.ingest_rows (
  id bigint generated by default as identity primary key,
  file_id uuid not null references public.ingest_files(id) on delete cascade,
  run_date date not null,
  row_index integer not null,
  row_json jsonb not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ingest_files_run_date_idx
  on public.ingest_files (run_date);

create index if not exists ingest_files_message_id_idx
  on public.ingest_files (message_id);

create index if not exists ingest_files_matched_topic_idx
  on public.ingest_files (matched_topic);

create index if not exists ingest_rows_file_id_idx
  on public.ingest_rows (file_id);

create index if not exists ingest_rows_run_date_idx
  on public.ingest_rows (run_date);
