drop view if exists public.export_rows_wide_operator;

create table if not exists public.operator_export_rows (
  row_id bigint generated by default as identity primary key,
  run_date date not null,
  topic text not null,
  report_date date,
  report_date_from date,
  report_date_to date,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text not null default 'aggregated',
  utm_term text not null default 'aggregated',
  visits numeric,
  users numeric,
  bounce_rate numeric,
  page_depth numeric,
  time_on_site_seconds numeric,
  robot_rate numeric,
  goal_1 numeric,
  goal_2 numeric,
  goal_3 numeric,
  goal_4 numeric,
  goal_5 numeric,
  goal_6 numeric,
  goal_7 numeric,
  goal_8 numeric,
  goal_9 numeric,
  goal_10 numeric,
  goal_11 numeric,
  goal_12 numeric,
  goal_13 numeric,
  goal_14 numeric,
  goal_15 numeric,
  goal_16 numeric,
  goal_17 numeric,
  goal_18 numeric,
  goal_19 numeric,
  goal_20 numeric,
  goal_21 numeric,
  goal_22 numeric,
  goal_23 numeric,
  goal_24 numeric,
  goal_25 numeric,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists operator_export_rows_run_date_idx
  on public.operator_export_rows (run_date);

create index if not exists operator_export_rows_report_date_idx
  on public.operator_export_rows (report_date);

truncate table public.operator_export_rows;

insert into public.operator_export_rows (
  run_date,
  topic,
  report_date,
  report_date_from,
  report_date_to,
  utm_source,
  utm_medium,
  utm_campaign,
  utm_content,
  utm_term,
  visits,
  users,
  bounce_rate,
  page_depth,
  time_on_site_seconds,
  robot_rate,
  goal_1,
  goal_2,
  goal_3,
  goal_4,
  goal_5,
  goal_6,
  goal_7,
  goal_8,
  goal_9,
  goal_10,
  goal_11,
  goal_12,
  goal_13,
  goal_14,
  goal_15,
  goal_16,
  goal_17,
  goal_18,
  goal_19,
  goal_20,
  goal_21,
  goal_22,
  goal_23,
  goal_24,
  goal_25
)
with target_rows as (
  select
    fr.fact_row_id,
    f.run_date,
    fr.topic,
    fr.report_date,
    fr.report_date_from,
    fr.report_date_to
  from public.fact_rows fr
  join public.ingest_files f
    on f.id = fr.source_file_id
  where fr.is_current = true
),
dimension_pivot as (
  select
    fd.fact_row_id,
    max(case when fd.dimension_key = 'utm_source' then fd.dimension_value end) as utm_source,
    max(case when fd.dimension_key = 'utm_medium' then fd.dimension_value end) as utm_medium,
    max(case when fd.dimension_key = 'utm_campaign' then fd.dimension_value end) as utm_campaign
  from public.fact_dimensions fd
  join target_rows tr
    on tr.fact_row_id = fd.fact_row_id
  group by fd.fact_row_id
),
metric_pivot as (
  select
    fm.fact_row_id,
    max(case when fm.metric_key = 'visits' then fm.metric_value end) as visits,
    max(case when fm.metric_key = 'users' then fm.metric_value end) as users,
    max(case when fm.metric_key = 'bounce_rate' then fm.metric_value end) as bounce_rate,
    max(case when fm.metric_key = 'page_depth' then fm.metric_value end) as page_depth,
    max(case when fm.metric_key = 'time_on_site_seconds' then fm.metric_value end) as time_on_site_seconds,
    max(case when fm.metric_key = 'robot_rate' then fm.metric_value end) as robot_rate,
    max(case when fm.metric_key = 'goal_1' then fm.metric_value end) as goal_1,
    max(case when fm.metric_key = 'goal_2' then fm.metric_value end) as goal_2,
    max(case when fm.metric_key = 'goal_3' then fm.metric_value end) as goal_3,
    max(case when fm.metric_key = 'goal_4' then fm.metric_value end) as goal_4,
    max(case when fm.metric_key = 'goal_5' then fm.metric_value end) as goal_5,
    max(case when fm.metric_key = 'goal_6' then fm.metric_value end) as goal_6,
    max(case when fm.metric_key = 'goal_7' then fm.metric_value end) as goal_7,
    max(case when fm.metric_key = 'goal_8' then fm.metric_value end) as goal_8,
    max(case when fm.metric_key = 'goal_9' then fm.metric_value end) as goal_9,
    max(case when fm.metric_key = 'goal_10' then fm.metric_value end) as goal_10,
    max(case when fm.metric_key = 'goal_11' then fm.metric_value end) as goal_11,
    max(case when fm.metric_key = 'goal_12' then fm.metric_value end) as goal_12,
    max(case when fm.metric_key = 'goal_13' then fm.metric_value end) as goal_13,
    max(case when fm.metric_key = 'goal_14' then fm.metric_value end) as goal_14,
    max(case when fm.metric_key = 'goal_15' then fm.metric_value end) as goal_15,
    max(case when fm.metric_key = 'goal_16' then fm.metric_value end) as goal_16,
    max(case when fm.metric_key = 'goal_17' then fm.metric_value end) as goal_17,
    max(case when fm.metric_key = 'goal_18' then fm.metric_value end) as goal_18,
    max(case when fm.metric_key = 'goal_19' then fm.metric_value end) as goal_19,
    max(case when fm.metric_key = 'goal_20' then fm.metric_value end) as goal_20,
    max(case when fm.metric_key = 'goal_21' then fm.metric_value end) as goal_21,
    max(case when fm.metric_key = 'goal_22' then fm.metric_value end) as goal_22,
    max(case when fm.metric_key = 'goal_23' then fm.metric_value end) as goal_23,
    max(case when fm.metric_key = 'goal_24' then fm.metric_value end) as goal_24,
    max(case when fm.metric_key = 'goal_25' then fm.metric_value end) as goal_25
  from public.fact_metrics fm
  join target_rows tr
    on tr.fact_row_id = fm.fact_row_id
  group by fm.fact_row_id
)
select
  tr.run_date,
  tr.topic,
  tr.report_date,
  tr.report_date_from,
  tr.report_date_to,
  dp.utm_source,
  dp.utm_medium,
  dp.utm_campaign,
  'aggregated'::text as utm_content,
  'aggregated'::text as utm_term,
  sum(mp.visits) as visits,
  sum(mp.users) as users,
  sum(case when mp.bounce_rate is not null then mp.bounce_rate * mp.visits end) as bounce_rate,
  sum(case when mp.page_depth is not null then mp.page_depth * mp.visits end) as page_depth,
  sum(case when mp.time_on_site_seconds is not null then mp.time_on_site_seconds * mp.visits end) as time_on_site_seconds,
  sum(case when mp.robot_rate is not null then mp.robot_rate * mp.visits end) as robot_rate,
  sum(mp.goal_1) as goal_1,
  sum(mp.goal_2) as goal_2,
  sum(mp.goal_3) as goal_3,
  sum(mp.goal_4) as goal_4,
  sum(mp.goal_5) as goal_5,
  sum(mp.goal_6) as goal_6,
  sum(mp.goal_7) as goal_7,
  sum(mp.goal_8) as goal_8,
  sum(mp.goal_9) as goal_9,
  sum(mp.goal_10) as goal_10,
  sum(mp.goal_11) as goal_11,
  sum(mp.goal_12) as goal_12,
  sum(mp.goal_13) as goal_13,
  sum(mp.goal_14) as goal_14,
  sum(mp.goal_15) as goal_15,
  sum(mp.goal_16) as goal_16,
  sum(mp.goal_17) as goal_17,
  sum(mp.goal_18) as goal_18,
  sum(mp.goal_19) as goal_19,
  sum(mp.goal_20) as goal_20,
  sum(mp.goal_21) as goal_21,
  sum(mp.goal_22) as goal_22,
  sum(mp.goal_23) as goal_23,
  sum(mp.goal_24) as goal_24,
  sum(mp.goal_25) as goal_25
from target_rows tr
left join dimension_pivot dp
  on dp.fact_row_id = tr.fact_row_id
left join metric_pivot mp
  on mp.fact_row_id = tr.fact_row_id
group by
  tr.run_date,
  tr.topic,
  tr.report_date,
  tr.report_date_from,
  tr.report_date_to,
  dp.utm_source,
  dp.utm_medium,
  dp.utm_campaign;
