create or replace view public.export_rows_wide_operator as
select
  erw.topic,
  erw.report_date,
  erw.report_date_from,
  erw.report_date_to,
  erw.utm_source,
  erw.utm_medium,
  erw.utm_campaign,
  'aggregated'::text as utm_content,
  'aggregated'::text as utm_term,
  sum(erw.visits) as visits,
  sum(erw.users) as users,
  sum(case when erw.bounce_rate is not null then erw.bounce_rate * erw.visits end) as bounce_rate,
  sum(case when erw.page_depth is not null then erw.page_depth * erw.visits end) as page_depth,
  sum(case when erw.time_on_site_seconds is not null then erw.time_on_site_seconds * erw.visits end) as time_on_site_seconds,
  sum(case when erw.robot_rate is not null then erw.robot_rate * erw.visits end) as robot_rate,
  sum(erw.goal_1) as goal_1,
  sum(erw.goal_2) as goal_2,
  sum(erw.goal_3) as goal_3,
  sum(erw.goal_4) as goal_4,
  sum(erw.goal_5) as goal_5,
  sum(erw.goal_6) as goal_6,
  sum(erw.goal_7) as goal_7,
  sum(erw.goal_8) as goal_8,
  sum(erw.goal_9) as goal_9,
  sum(erw.goal_10) as goal_10,
  sum(erw.goal_11) as goal_11,
  sum(erw.goal_12) as goal_12,
  sum(erw.goal_13) as goal_13,
  sum(erw.goal_14) as goal_14,
  sum(erw.goal_15) as goal_15,
  sum(erw.goal_16) as goal_16,
  sum(erw.goal_17) as goal_17,
  sum(erw.goal_18) as goal_18,
  sum(erw.goal_19) as goal_19,
  sum(erw.goal_20) as goal_20,
  sum(erw.goal_21) as goal_21,
  sum(erw.goal_22) as goal_22,
  sum(erw.goal_23) as goal_23,
  sum(erw.goal_24) as goal_24,
  sum(erw.goal_25) as goal_25
from public.export_rows_wide erw
group by
  erw.topic,
  erw.report_date,
  erw.report_date_from,
  erw.report_date_to,
  erw.utm_source,
  erw.utm_medium,
  erw.utm_campaign;
